service: split-stack-documentation-test-v2

plugins:
  - serverless-plugin-split-stacks
  - serverless-aws-documentation

custom:
  documentation: ${file(documentation.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: stage
  region: us-east-1
  profile: cjs-stage

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: things
          method: get
          cors: true
          documentation:
            summary: "Get things"
            tags:
              - "get-things"
            methodResponses:
              -
                statusCode: "200"
                responseModels:
                  "application/json": "GetRequest"
              -
                statusCode: "500"
                responseModels:
                  "application/json": "ErrorResponse"
      - http:
          path: things
          method: post
          cors: true
          documentation:
            summary: "Creates a thing"
            tags:
              - "create-things"
            requestModels:
              "application/json": "CreateRequest"
            methodResponses:
              -
                statusCode: "201"
                responseModels:
                  "application/json": "CreateResponse"
              -
                statusCode: "500"
                responseModels:
                  "application/json": "ErrorResponse"